### ISSUE TITLE
is there a way to run it without docker?

### ISSUE THREAD

**Issue by rkopplin** [nnewman/stewie#4]
if yes, can you please describe it?

**Comment by nnewman** [comment]
There certainly is! I recommend using a virtualenv. Use the following:

``` bash
$ pip install -e git+https://github.com/nnewman/stewie.git@master#egg=stewie
$ curl https://raw.githubusercontent.com/nnewman/stewie/master/stewie/config.template.py > config.py
$ vim config.py  # edit and set your team ID from lattermost
$ gunicorn -b 0.0.0.0:8043 stewie.server:app
```

I'll be adding this to the README soon.

**Comment by nnewman** [comment]
Also, Python3 is required.

**Comment by rkopplin** [comment]
starting virtualenv with python3
also python 3 is used by typing python -V.

seems that stewie is still using python 2

 gunicorn -b 0.0.0.0:8043 stewie.server:app
2016-10-11 09:34:37 [6671] [INFO] Starting gunicorn 18.0
2016-10-11 09:34:37 [6671] [INFO] Listening at: http://0.0.0.0:8043 (6671)
2016-10-11 09:34:37 [6671] [INFO] Using worker: sync
2016-10-11 09:34:37 [6676] [INFO] Booting worker with pid: 6676
2016-10-11 09:34:37 [6676] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/home/stewie/src/stewie/stewie/server.py", line 11, in <module>
    from .stewie import Stewie, command_processor
  File "/home/stewie/src/stewie/stewie/stewie.py", line 10, in <module>
    from plugins import yelp
  File "/home/stewie/src/stewie/stewie/plugins/yelp.py", line 12, in <module>
    import urllib.request
ImportError: No module named request
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/home/stewie/src/stewie/stewie/server.py", line 11, in <module>
    from .stewie import Stewie, command_processor
  File "/home/stewie/src/stewie/stewie/stewie.py", line 10, in <module>
    from plugins import yelp
  File "/home/stewie/src/stewie/stewie/plugins/yelp.py", line 12, in <module>
    import urllib.request
ImportError: No module named request
2016-10-11 09:34:37 [6676] [INFO] Worker exiting (pid: 6676)
2016-10-11 09:34:37 [6671] [INFO] Shutting down: Master
2016-10-11 09:34:37 [6671] [INFO] Reason: Worker failed to boot.
(stewie) [user@host]# python -V
Python 3.5.2

**Comment by rkopplin** [comment]
forced gunicorn using python 3 by creating a config file for gunicorn

starting with: 

 /home/stewie/bin/gunicorn -c /home/stewie/gunicorn_config.py stewie.server:app
[2016-10-11 10:00:18 +0200] [10139] [INFO] Starting gunicorn 19.6.0
[2016-10-11 10:00:18 +0200] [10139] [INFO] Listening at: http://0.0.0.0:8083 (10139)
[2016-10-11 10:00:18 +0200] [10139] [INFO] Using worker: sync
[2016-10-11 10:00:18 +0200] [10142] [INFO] Booting worker with pid: 10142
[2016-10-11 10:00:18 +0200] [10143] [INFO] Booting worker with pid: 10143
[2016-10-11 10:00:18 +0200] [10142] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/stewie/lib/python3.5/site-packages/stewie-0.9.1-py3.5.egg/stewie/stewie.py", line 8, in <module>
    from .plugins import yelp
ImportError: No module named 'stewie.plugins'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stewie/lib/python3.5/site-packages/gunicorn/arbiter.py", line 557, in spawn_worker
    worker.init_process()
  File "/home/stewie/lib/python3.5/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/home/stewie/lib/python3.5/site-packages/gunicorn/workers/base.py", line 136, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/stewie/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/stewie/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/stewie/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/stewie/lib/python3.5/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/home/stewie/lib/python3.5/site-packages/stewie-0.9.1-py3.5.egg/stewie/server.py", line 11, in <module>
    from .stewie import Stewie, command_processor
  File "/home/stewie/lib/python3.5/site-packages/stewie-0.9.1-py3.5.egg/stewie/stewie.py", line 10, in <module>
    from plugins import yelp
ImportError: No module named 'plugins'
[2016-10-11 10:00:18 +0200] [10142] [INFO] Worker exiting (pid: 10142)
[2016-10-11 10:00:18 +0200] [10146] [INFO] Booting worker with pid: 10146
[2016-10-11 10:00:18 +0200] [10143] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/stewie/lib/python3.5/site-packages/stewie-0.9.1-py3.5.egg/stewie/stewie.py", line 8, in <module>
    from .plugins import yelp
ImportError: No module named 'stewie.plugins'

**Comment by rkopplin** [comment]
getting: 

{
  "attachments": [],
  "response_type": "ephemeral",
  "text": "Command None is not found in team None"
}

by calling guncorn url.

what do i have to enter at mattermost token? outgoing hook token? how to setup the outgoing specially for stewie?
